import {
	type typeDocumentIdentification,
	type typeOrganization,
	type typeRegime,
	type typeLiability,
	type taxDetail,
	type creditNoteCorrectionsType,
	type debitNoteCorrectionsType,
	type VillingOrganizationType,
	type PosCreditNoteCorrectionType,
} from './enums';

export const identifications = [
	{ value: 'nit', label: 'NIT' },
	{ value: 'cc', label: 'Cédula de ciudadanía' },
	{ value: 'ce', label: 'Cédula de extranjería' },
	{ value: 'ps', label: 'Pasaporte' },
	{ value: 'te', label: 'Tarjeta de extranjería' },
	{ value: 'ti', label: 'Tarjeta de identidad' },
	{ value: 'die', label: 'Documento de identificación extranjero' },
	{ value: 'rc', label: 'Registro civil' },
	{ value: 'nit_ext', label: 'NIT de otro país' },
	{ value: 'nuip', label: 'NUIP' },
] satisfies Array<{
	value: keyof typeof typeDocumentIdentification;
	label: string;
}>;
export const soenacIdentificationsMapper = {
	nit: 6,
	cc: 3,
	ce: 5,
	ps: 7,
	te: 4,
	ti: 2,
	die: 8,
	rc: 1,
	nit_ext: 9,
	nuip: 10,
} satisfies Record<keyof typeof typeDocumentIdentification, number>;

export const typeOrganizations = [
	{ value: 'juridical', label: 'Persona jurídica' },
	{ value: 'natural', label: 'Persona natural' },
] satisfies Array<{ value: keyof typeof typeOrganization; label: string }>;
export const soenacTypeOrganizationsMapper = {
	juridical: 1,
	natural: 2,
} satisfies Record<keyof typeof typeOrganization, number>;

export const typeRegimes = [
	{ value: 'iva', label: 'Impuesto sobre las ventas - IVA' },
	{ value: 'noIva', label: 'No responsable de IVA' },
] satisfies Array<{ value: keyof typeof typeRegime; label: string }>;
export const soenacTypeRegimesMapper = {
	iva: 1,
	noIva: 2,
} satisfies Record<keyof typeof typeRegime, number>;

export const typeLiabilities = [
	{ value: 'noLiability', label: 'No aplica - Otros' },
	{ value: 'simpleRegime', label: 'Régimen simple de tributación' },
	{ value: 'selfRetainer', label: 'Autoretenedor' },
	{ value: 'ivaRetentionAgent', label: 'Agente de retención de IVA' },
	{ value: 'bigTaxPayer', label: 'Gran contribuyente' },
] satisfies Array<{ value: keyof typeof typeLiability; label: string }>;
export const soenacTypeLiabilitiesMapper = {
	noLiability: 29,
	simpleRegime: 20,
	selfRetainer: 7,
	ivaRetentionAgent: 12,
	bigTaxPayer: 5,
} satisfies Record<keyof typeof typeLiability, number>;

export const taxDetails = [
	{ value: 'iva', label: 'IVA - Impuesto sobre las ventas' },
	{ value: 'inc', label: 'INC - Impuesto al consumo' },
	{ value: 'ivaAndInc', label: 'IVA y INC' },
	{ value: 'noTax', label: 'No aplica' },
] satisfies Array<{ value: keyof typeof taxDetail; label: string }>;
export const soenacTaxDetailsMapper = {
	iva: 1,
	inc: 2,
	ivaAndInc: 4,
	noTax: 5,
} satisfies Record<keyof typeof taxDetail, number>;

export const creditNoteCorrectionResponses = [
	{
		value: 'return',
		label:
			'Devolución parcial de los bienes y/o no aceptación parcial del servicio',
	},
	{ value: 'cancel', label: 'Anulación de factura electrónica' },
	{ value: 'discount', label: 'Rebaja  o descuento parcial o total' },
	{ value: 'priceAdjustment', label: 'Ajuste de precio' },
	{ value: 'other', label: 'Otros' },
] satisfies Array<{
	value: keyof typeof creditNoteCorrectionsType;
	label: string;
}>;
export const soenacCreditNoteCorrectionResponsesMapper = {
	return: 1,
	cancel: 2,
	discount: 3,
	priceAdjustment: 4,
	other: 5,
} satisfies Record<keyof typeof creditNoteCorrectionsType, number>;

export const debitNoteCorrectionResponses = [
	{
		value: 'interest',
		label: 'Intereses',
	},
	{ value: 'expenses', label: 'Gastos por cobrar' },
	{ value: 'valueChange', label: 'Cambio del valor' },
	{ value: 'other', label: 'Otros' },
] satisfies Array<{
	value: keyof typeof debitNoteCorrectionsType;
	label: string;
}>;
export const soenacDebitNoteCorrectionResponsesMapper = {
	interest: 7,
	expenses: 8,
	valueChange: 9,
	other: 10,
} satisfies Record<keyof typeof debitNoteCorrectionsType, number>;

export const municipalities = [
	{ value: 1, label: 'Medellín' },
	{ value: 2, label: 'Abejorral' },
	{ value: 3, label: 'Abriaquí' },
	{ value: 4, label: 'Alejandría' },
	{ value: 5, label: 'Amagá' },
	{ value: 6, label: 'Amalfi' },
	{ value: 7, label: 'Andes' },
	{ value: 8, label: 'Angelópolis' },
	{ value: 9, label: 'Angostura' },
	{ value: 10, label: 'Anorí' },
	{ value: 11, label: 'Santa Fé De Antioquia' },
	{ value: 12, label: 'Anzá' },
	{ value: 13, label: 'Apartadó' },
	{ value: 14, label: 'Arboletes' },
	{ value: 15, label: 'Argelia' },
	{ value: 16, label: 'Armenia' },
	{ value: 17, label: 'Barbosa' },
	{ value: 18, label: 'Belmira' },
	{ value: 19, label: 'Bello' },
	{ value: 20, label: 'Betania' },
	{ value: 21, label: 'Betulia' },
	{ value: 22, label: 'Ciudad Bolívar ' },
	{ value: 23, label: 'Briceño' },
	{ value: 24, label: 'Buriticá' },
	{ value: 25, label: 'Cáceres' },
	{ value: 26, label: 'Caicedo' },
	{ value: 27, label: 'Caldas' },
	{ value: 28, label: 'Campamento' },
	{ value: 29, label: 'Cañasgordas' },
	{ value: 30, label: 'Caracolí' },
	{ value: 31, label: 'Caramanta' },
	{ value: 32, label: 'Carepa' },
	{ value: 33, label: 'El Carmen De Viboral' },
	{ value: 34, label: 'Carolina' },
	{ value: 35, label: 'Caucasia' },
	{ value: 36, label: 'Chigorodó' },
	{ value: 37, label: 'Cisneros' },
	{ value: 38, label: 'Cocorná' },
	{ value: 39, label: 'Concepción' },
	{ value: 40, label: 'Concordia' },
	{ value: 41, label: 'Copacabana' },
	{ value: 42, label: 'Dabeiba' },
	{ value: 43, label: 'Donmatías' },
	{ value: 44, label: 'Ebéjico' },
	{ value: 45, label: 'El Bagre ' },
	{ value: 46, label: 'Entrerríos' },
	{ value: 47, label: 'Envigado' },
	{ value: 48, label: 'Fredonia' },
	{ value: 49, label: 'Frontino' },
	{ value: 50, label: 'Giraldo' },
	{ value: 51, label: 'Girardota' },
	{ value: 52, label: 'Gómez Plata ' },
	{ value: 53, label: 'Granada' },
	{ value: 54, label: 'Guadalupe' },
	{ value: 55, label: 'Guarne' },
	{ value: 56, label: 'Guatapé' },
	{ value: 57, label: 'Heliconia' },
	{ value: 58, label: 'Hispania' },
	{ value: 59, label: 'Itagüí' },
	{ value: 60, label: 'Ituango' },
	{ value: 61, label: 'Jardín' },
	{ value: 62, label: 'Jericó' },
	{ value: 63, label: 'La Ceja ' },
	{ value: 64, label: 'La Estrella ' },
	{ value: 65, label: 'La Pintada ' },
	{ value: 66, label: 'La Unión ' },
	{ value: 67, label: 'Liborina' },
	{ value: 68, label: 'Maceo' },
	{ value: 69, label: 'Marinilla' },
	{ value: 70, label: 'Montebello' },
	{ value: 71, label: 'Murindó' },
	{ value: 72, label: 'Mutatá' },
	{ value: 73, label: 'Nariño' },
	{ value: 74, label: 'Necoclí' },
	{ value: 75, label: 'Nechí' },
	{ value: 76, label: 'Olaya' },
	{ value: 77, label: 'Peñol' },
	{ value: 78, label: 'Peque' },
	{ value: 79, label: 'Pueblorrico' },
	{ value: 80, label: 'Puerto Berrío ' },
	{ value: 81, label: 'Puerto Nare ' },
	{ value: 82, label: 'Puerto Triunfo ' },
	{ value: 83, label: 'Remedios' },
	{ value: 84, label: 'Retiro' },
	{ value: 85, label: 'Rionegro' },
	{ value: 86, label: 'Sabanalarga' },
	{ value: 87, label: 'Sabaneta' },
	{ value: 88, label: 'Salgar' },
	{ value: 89, label: 'San Andrés De Cuerquía' },
	{ value: 90, label: 'San Carlos ' },
	{ value: 91, label: 'San Francisco ' },
	{ value: 92, label: 'San Jerónimo ' },
	{ value: 93, label: 'San José De La Montaña ' },
	{ value: 94, label: 'San Juan De Urabá' },
	{ value: 95, label: 'San Luis ' },
	{ value: 96, label: 'San Pedro De Los Milagros ' },
	{ value: 97, label: 'San Pedro De Urabá' },
	{ value: 98, label: 'San Rafael ' },
	{ value: 99, label: 'San Roque ' },
	{ value: 100, label: 'San Vicente Ferrer' },
	{ value: 101, label: 'Santa Bárbara ' },
	{ value: 102, label: 'Santa Rosa De Osos' },
	{ value: 103, label: 'Santo Domingo ' },
	{ value: 104, label: 'El Santuario ' },
	{ value: 105, label: 'Segovia' },
	{ value: 106, label: 'Sonsón' },
	{ value: 107, label: 'Sopetrán' },
	{ value: 108, label: 'Támesis' },
	{ value: 109, label: 'Tarazá' },
	{ value: 110, label: 'Tarso' },
	{ value: 111, label: 'Titiribí' },
	{ value: 112, label: 'Toledo' },
	{ value: 113, label: 'Turbo' },
	{ value: 114, label: 'Uramita' },
	{ value: 115, label: 'Urrao' },
	{ value: 116, label: 'Valdivia' },
	{ value: 117, label: 'Valparaíso' },
	{ value: 118, label: 'Vegachí' },
	{ value: 119, label: 'Venecia' },
	{ value: 120, label: 'Vigía Del Fuerte' },
	{ value: 121, label: 'Yalí' },
	{ value: 122, label: 'Yarumal' },
	{ value: 123, label: 'Yolombó' },
	{ value: 124, label: 'Yondó' },
	{ value: 125, label: 'Zaragoza' },
	{ value: 126, label: 'Barranquilla' },
	{ value: 127, label: 'Baranoa' },
	{ value: 128, label: 'Campo De La Cruz' },
	{ value: 129, label: 'Candelaria' },
	{ value: 130, label: 'Galapa' },
	{ value: 131, label: 'Juan De Acosta' },
	{ value: 132, label: 'Luruaco' },
	{ value: 133, label: 'Malambo' },
	{ value: 134, label: 'Manatí' },
	{ value: 135, label: 'Palmar De Varela' },
	{ value: 136, label: 'Piojó' },
	{ value: 137, label: 'Polonuevo' },
	{ value: 138, label: 'Ponedera' },
	{ value: 139, label: 'Puerto Colombia ' },
	{ value: 140, label: 'Repelón' },
	{ value: 141, label: 'Sabanagrande' },
	{ value: 142, label: 'Sabanalarga' },
	{ value: 143, label: 'Santa Lucía ' },
	{ value: 144, label: 'Santo Tomás ' },
	{ value: 145, label: 'Soledad' },
	{ value: 146, label: 'Suan' },
	{ value: 147, label: 'Tubará' },
	{ value: 148, label: 'Usiacurí' },
	{ value: 149, label: 'Bogotá, D.C. ' },
	{ value: 150, label: 'Cartagena De Indias' },
	{ value: 151, label: 'Achí' },
	{ value: 152, label: 'Altos Del Rosario' },
	{ value: 153, label: 'Arenal' },
	{ value: 154, label: 'Arjona' },
	{ value: 155, label: 'Arroyohondo' },
	{ value: 156, label: 'Barranco De Loba' },
	{ value: 157, label: 'Calamar' },
	{ value: 158, label: 'Cantagallo' },
	{ value: 159, label: 'Cicuco' },
	{ value: 160, label: 'Córdoba' },
	{ value: 161, label: 'Clemencia' },
	{ value: 162, label: 'El Carmen De Bolívar' },
	{ value: 163, label: 'El Guamo ' },
	{ value: 164, label: 'El Peñón ' },
	{ value: 165, label: 'Hatillo De Loba' },
	{ value: 166, label: 'Magangué' },
	{ value: 167, label: 'Mahates' },
	{ value: 168, label: 'Margarita' },
	{ value: 169, label: 'María La Baja' },
	{ value: 170, label: 'Montecristo' },
	{ value: 171, label: 'Mompós' },
	{ value: 172, label: 'Morales' },
	{ value: 173, label: 'Norosí' },
	{ value: 174, label: 'Pinillos' },
	{ value: 175, label: 'Regidor' },
	{ value: 176, label: 'Río Viejo ' },
	{ value: 177, label: 'San Cristóbal ' },
	{ value: 178, label: 'San Estanislao ' },
	{ value: 179, label: 'San Fernando ' },
	{ value: 180, label: 'San Jacinto ' },
	{ value: 181, label: 'San Jacinto Del Cauca' },
	{ value: 182, label: 'San Juan Nepomuceno' },
	{ value: 183, label: 'San Martín De Loba' },
	{ value: 184, label: 'San Pablo ' },
	{ value: 185, label: 'Santa Catalina ' },
	{ value: 186, label: 'Santa Rosa ' },
	{ value: 187, label: 'Santa Rosa Del Sur' },
	{ value: 188, label: 'Simití' },
	{ value: 189, label: 'Soplaviento' },
	{ value: 190, label: 'Talaigua Nuevo ' },
	{ value: 191, label: 'Tiquisio' },
	{ value: 192, label: 'Turbaco' },
	{ value: 193, label: 'Turbaná' },
	{ value: 194, label: 'Villanueva' },
	{ value: 195, label: 'Zambrano' },
	{ value: 196, label: 'Tunja' },
	{ value: 197, label: 'Almeida' },
	{ value: 198, label: 'Aquitania' },
	{ value: 199, label: 'Arcabuco' },
	{ value: 200, label: 'Belén' },
	{ value: 201, label: 'Berbeo' },
	{ value: 202, label: 'Betéitiva' },
	{ value: 203, label: 'Boavita' },
	{ value: 204, label: 'Boyacá' },
	{ value: 205, label: 'Briceño' },
	{ value: 206, label: 'Buenavista' },
	{ value: 207, label: 'Busbanzá' },
	{ value: 208, label: 'Caldas' },
	{ value: 209, label: 'Campohermoso' },
	{ value: 210, label: 'Cerinza' },
	{ value: 211, label: 'Chinavita' },
	{ value: 212, label: 'Chiquinquirá' },
	{ value: 213, label: 'Chiscas' },
	{ value: 214, label: 'Chita' },
	{ value: 215, label: 'Chitaraque' },
	{ value: 216, label: 'Chivatá' },
	{ value: 217, label: 'Ciénega' },
	{ value: 218, label: 'Cómbita' },
	{ value: 219, label: 'Coper' },
	{ value: 220, label: 'Corrales' },
	{ value: 221, label: 'Covarachía' },
	{ value: 222, label: 'Cubará' },
	{ value: 223, label: 'Cucaita' },
	{ value: 224, label: 'Cuítiva' },
	{ value: 225, label: 'Chíquiza' },
	{ value: 226, label: 'Chivor' },
	{ value: 227, label: 'Duitama' },
	{ value: 228, label: 'El Cocuy ' },
	{ value: 229, label: 'El Espino ' },
	{ value: 230, label: 'Firavitoba' },
	{ value: 231, label: 'Floresta' },
	{ value: 232, label: 'Gachantivá' },
	{ value: 233, label: 'Gámeza' },
	{ value: 234, label: 'Garagoa' },
	{ value: 235, label: 'Guacamayas' },
	{ value: 236, label: 'Guateque' },
	{ value: 237, label: 'Guayatá' },
	{ value: 238, label: 'Güicán De La Sierra' },
	{ value: 239, label: 'Iza' },
	{ value: 240, label: 'Jenesano' },
	{ value: 241, label: 'Jericó' },
	{ value: 242, label: 'Labranzagrande' },
	{ value: 243, label: 'La Capilla ' },
	{ value: 244, label: 'La Victoria ' },
	{ value: 245, label: 'La Uvita ' },
	{ value: 246, label: 'Villa De Leyva' },
	{ value: 247, label: 'Macanal' },
	{ value: 248, label: 'Maripí' },
	{ value: 249, label: 'Miraflores' },
	{ value: 250, label: 'Mongua' },
	{ value: 251, label: 'Monguí' },
	{ value: 252, label: 'Moniquirá' },
	{ value: 253, label: 'Motavita' },
	{ value: 254, label: 'Muzo' },
	{ value: 255, label: 'Nobsa' },
	{ value: 256, label: 'Nuevo Colón ' },
	{ value: 257, label: 'Oicatá' },
	{ value: 258, label: 'Otanche' },
	{ value: 259, label: 'Pachavita' },
	{ value: 260, label: 'Páez' },
	{ value: 261, label: 'Paipa' },
	{ value: 262, label: 'Pajarito' },
	{ value: 263, label: 'Panqueba' },
	{ value: 264, label: 'Pauna' },
	{ value: 265, label: 'Paya' },
	{ value: 266, label: 'Paz De Río' },
	{ value: 267, label: 'Pesca' },
	{ value: 268, label: 'Pisba' },
	{ value: 269, label: 'Puerto Boyacá ' },
	{ value: 270, label: 'Quípama' },
	{ value: 271, label: 'Ramiriquí' },
	{ value: 272, label: 'Ráquira' },
	{ value: 273, label: 'Rondón' },
	{ value: 274, label: 'Saboyá' },
	{ value: 275, label: 'Sáchica' },
	{ value: 276, label: 'Samacá' },
	{ value: 277, label: 'San Eduardo ' },
	{ value: 278, label: 'San José De Pare' },
	{ value: 279, label: 'San Luis De Gaceno' },
	{ value: 280, label: 'San Mateo ' },
	{ value: 281, label: 'San Miguel De Sema' },
	{ value: 282, label: 'San Pablo De Borbur' },
	{ value: 283, label: 'Santana' },
	{ value: 284, label: 'Santa María ' },
	{ value: 285, label: 'Santa Rosa De Viterbo' },
	{ value: 286, label: 'Santa Sofía ' },
	{ value: 287, label: 'Sativanorte' },
	{ value: 288, label: 'Sativasur' },
	{ value: 289, label: 'Siachoque' },
	{ value: 290, label: 'Soatá' },
	{ value: 291, label: 'Socotá' },
	{ value: 292, label: 'Socha' },
	{ value: 293, label: 'Sogamoso' },
	{ value: 294, label: 'Somondoco' },
	{ value: 295, label: 'Sora' },
	{ value: 296, label: 'Sotaquirá' },
	{ value: 297, label: 'Soracá' },
	{ value: 298, label: 'Susacón' },
	{ value: 299, label: 'Sutamarchán' },
	{ value: 300, label: 'Sutatenza' },
	{ value: 301, label: 'Tasco' },
	{ value: 302, label: 'Tenza' },
	{ value: 303, label: 'Tibaná' },
	{ value: 304, label: 'Tibasosa' },
	{ value: 305, label: 'Tinjacá' },
	{ value: 306, label: 'Tipacoque' },
	{ value: 307, label: 'Toca' },
	{ value: 308, label: 'Togüí' },
	{ value: 309, label: 'Tópaga' },
	{ value: 310, label: 'Tota' },
	{ value: 311, label: 'Tununguá' },
	{ value: 312, label: 'Turmequé' },
	{ value: 313, label: 'Tuta' },
	{ value: 314, label: 'Tutazá' },
	{ value: 315, label: 'Úmbita' },
	{ value: 316, label: 'Ventaquemada' },
	{ value: 317, label: 'Viracachá' },
	{ value: 318, label: 'Zetaquira' },
	{ value: 319, label: 'Manizales' },
	{ value: 320, label: 'Aguadas' },
	{ value: 321, label: 'Anserma' },
	{ value: 322, label: 'Aranzazu' },
	{ value: 323, label: 'Belalcázar' },
	{ value: 324, label: 'Chinchiná' },
	{ value: 325, label: 'Filadelfia' },
	{ value: 326, label: 'La Dorada ' },
	{ value: 327, label: 'La Merced ' },
	{ value: 328, label: 'Manzanares' },
	{ value: 329, label: 'Marmato' },
	{ value: 330, label: 'Marquetalia' },
	{ value: 331, label: 'Marulanda' },
	{ value: 332, label: 'Neira' },
	{ value: 333, label: 'Norcasia' },
	{ value: 334, label: 'Pácora' },
	{ value: 335, label: 'Palestina' },
	{ value: 336, label: 'Pensilvania' },
	{ value: 337, label: 'Riosucio' },
	{ value: 338, label: 'Risaralda' },
	{ value: 339, label: 'Salamina' },
	{ value: 340, label: 'Samaná' },
	{ value: 341, label: 'San José ' },
	{ value: 342, label: 'Supía' },
	{ value: 343, label: 'Victoria' },
	{ value: 344, label: 'Villamaría' },
	{ value: 345, label: 'Viterbo' },
	{ value: 346, label: 'Florencia' },
	{ value: 347, label: 'Albania' },
	{ value: 348, label: 'Belén De Los Andaquíes' },
	{ value: 349, label: 'Cartagena Del Chairá' },
	{ value: 350, label: 'Curillo' },
	{ value: 351, label: 'El Doncello ' },
	{ value: 352, label: 'El Paujíl ' },
	{ value: 353, label: 'La Montañita ' },
	{ value: 354, label: 'Milán' },
	{ value: 355, label: 'Morelia' },
	{ value: 356, label: 'Puerto Rico ' },
	{ value: 357, label: 'San José Del Fragua' },
	{ value: 358, label: 'San Vicente Del Caguán' },
	{ value: 359, label: 'Solano' },
	{ value: 360, label: 'Solita' },
	{ value: 361, label: 'Valparaíso' },
	{ value: 362, label: 'Popayán' },
	{ value: 363, label: 'Almaguer' },
	{ value: 364, label: 'Argelia' },
	{ value: 365, label: 'Balboa' },
	{ value: 366, label: 'Bolívar' },
	{ value: 367, label: 'Buenos Aires ' },
	{ value: 368, label: 'Cajibío' },
	{ value: 369, label: 'Caldono' },
	{ value: 370, label: 'Caloto' },
	{ value: 371, label: 'Corinto' },
	{ value: 372, label: 'El Tambo ' },
	{ value: 373, label: 'Florencia' },
	{ value: 374, label: 'Guachené' },
	{ value: 375, label: 'Guapí' },
	{ value: 376, label: 'Inzá' },
	{ value: 377, label: 'Jambaló' },
	{ value: 378, label: 'La Sierra ' },
	{ value: 379, label: 'La Vega ' },
	{ value: 380, label: 'López De Micay' },
	{ value: 381, label: 'Mercaderes' },
	{ value: 382, label: 'Miranda' },
	{ value: 383, label: 'Morales' },
	{ value: 384, label: 'Padilla' },
	{ value: 385, label: 'Páez' },
	{ value: 386, label: 'Patía' },
	{ value: 387, label: 'Piamonte' },
	{ value: 388, label: 'Piendamó - Tunía' },
	{ value: 389, label: 'Puerto Tejada ' },
	{ value: 390, label: 'Puracé' },
	{ value: 391, label: 'Rosas' },
	{ value: 392, label: 'San Sebastián ' },
	{ value: 393, label: 'Santander De Quilichao' },
	{ value: 394, label: 'Santa Rosa ' },
	{ value: 395, label: 'Silvia' },
	{ value: 396, label: 'Sotara' },
	{ value: 397, label: 'Suárez' },
	{ value: 398, label: 'Sucre' },
	{ value: 399, label: 'Timbío' },
	{ value: 400, label: 'Timbiquí' },
	{ value: 401, label: 'Toribío' },
	{ value: 402, label: 'Totoró' },
	{ value: 403, label: 'Villa Rica ' },
	{ value: 404, label: 'Valledupar' },
	{ value: 405, label: 'Aguachica' },
	{ value: 406, label: 'Agustín Codazzi ' },
	{ value: 407, label: 'Astrea' },
	{ value: 408, label: 'Becerril' },
	{ value: 409, label: 'Bosconia' },
	{ value: 410, label: 'Chimichagua' },
	{ value: 411, label: 'Chiriguaná' },
	{ value: 412, label: 'Curumaní' },
	{ value: 413, label: 'El Copey ' },
	{ value: 414, label: 'El Paso ' },
	{ value: 415, label: 'Gamarra' },
	{ value: 416, label: 'González' },
	{ value: 417, label: 'La Gloria ' },
	{ value: 418, label: 'La Jagua De Ibirico' },
	{ value: 419, label: 'Manaure Balcón Del Cesar' },
	{ value: 420, label: 'Pailitas' },
	{ value: 421, label: 'Pelaya' },
	{ value: 422, label: 'Pueblo Bello ' },
	{ value: 423, label: 'Río De Oro' },
	{ value: 424, label: 'La Paz ' },
	{ value: 425, label: 'San Alberto ' },
	{ value: 426, label: 'San Diego ' },
	{ value: 427, label: 'San Martín ' },
	{ value: 428, label: 'Tamalameque' },
	{ value: 429, label: 'Montería' },
	{ value: 430, label: 'Ayapel' },
	{ value: 431, label: 'Buenavista' },
	{ value: 432, label: 'Canalete' },
	{ value: 433, label: 'Cereté' },
	{ value: 434, label: 'Chimá' },
	{ value: 435, label: 'Chinú' },
	{ value: 436, label: 'Ciénaga De Oro' },
	{ value: 437, label: 'Cotorra' },
	{ value: 438, label: 'La Apartada ' },
	{ value: 439, label: 'Lorica' },
	{ value: 440, label: 'Los Córdobas ' },
	{ value: 441, label: 'Momil' },
	{ value: 442, label: 'Montelíbano' },
	{ value: 443, label: 'Moñitos' },
	{ value: 444, label: 'Planeta Rica ' },
	{ value: 445, label: 'Pueblo Nuevo ' },
	{ value: 446, label: 'Puerto Escondido ' },
	{ value: 447, label: 'Puerto Libertador ' },
	{ value: 448, label: 'Purísima De La Concepción' },
	{ value: 449, label: 'Sahagún' },
	{ value: 450, label: 'San Andrés De Sotavento' },
	{ value: 451, label: 'San Antero ' },
	{ value: 452, label: 'San Bernardo Del Viento' },
	{ value: 453, label: 'San Carlos ' },
	{ value: 454, label: 'San José De Uré' },
	{ value: 455, label: 'San Pelayo ' },
	{ value: 456, label: 'Tierralta' },
	{ value: 457, label: 'Tuchín' },
	{ value: 458, label: 'Valencia' },
	{ value: 459, label: 'Agua De Dios' },
	{ value: 460, label: 'Albán' },
	{ value: 461, label: 'Anapoima' },
	{ value: 462, label: 'Anolaima' },
	{ value: 463, label: 'Arbeláez' },
	{ value: 464, label: 'Beltrán' },
	{ value: 465, label: 'Bituima' },
	{ value: 466, label: 'Bojacá' },
	{ value: 467, label: 'Cabrera' },
	{ value: 468, label: 'Cachipay' },
	{ value: 469, label: 'Cajicá' },
	{ value: 470, label: 'Caparrapí' },
	{ value: 471, label: 'Cáqueza' },
	{ value: 472, label: 'Carmen De Carupa' },
	{ value: 473, label: 'Chaguaní' },
	{ value: 474, label: 'Chía' },
	{ value: 475, label: 'Chipaque' },
	{ value: 476, label: 'Choachí' },
	{ value: 477, label: 'Chocontá' },
	{ value: 478, label: 'Cogua' },
	{ value: 479, label: 'Cota' },
	{ value: 480, label: 'Cucunubá' },
	{ value: 481, label: 'El Colegio ' },
	{ value: 482, label: 'El Peñón ' },
	{ value: 483, label: 'El Rosal ' },
	{ value: 484, label: 'Facatativá' },
	{ value: 485, label: 'Fómeque' },
	{ value: 486, label: 'Fosca' },
	{ value: 487, label: 'Funza' },
	{ value: 488, label: 'Fúquene' },
	{ value: 489, label: 'Fusagasugá' },
	{ value: 490, label: 'Gachalá' },
	{ value: 491, label: 'Gachancipá' },
	{ value: 492, label: 'Gachetá' },
	{ value: 493, label: 'Gama' },
	{ value: 494, label: 'Girardot' },
	{ value: 495, label: 'Granada' },
	{ value: 496, label: 'Guachetá' },
	{ value: 497, label: 'Guaduas' },
	{ value: 498, label: 'Guasca' },
	{ value: 499, label: 'Guataquí' },
	{ value: 500, label: 'Guatavita' },
	{ value: 501, label: 'Guayabal De Síquima' },
	{ value: 502, label: 'Guayabetal' },
	{ value: 503, label: 'Gutiérrez' },
	{ value: 504, label: 'Jerusalén' },
	{ value: 505, label: 'Junín' },
	{ value: 506, label: 'La Calera ' },
	{ value: 507, label: 'La Mesa ' },
	{ value: 508, label: 'La Palma ' },
	{ value: 509, label: 'La Peña ' },
	{ value: 510, label: 'La Vega ' },
	{ value: 511, label: 'Lenguazaque' },
	{ value: 512, label: 'Machetá' },
	{ value: 513, label: 'Madrid' },
	{ value: 514, label: 'Manta' },
	{ value: 515, label: 'Medina' },
	{ value: 516, label: 'Mosquera' },
	{ value: 517, label: 'Nariño' },
	{ value: 518, label: 'Nemocón' },
	{ value: 519, label: 'Nilo' },
	{ value: 520, label: 'Nimaima' },
	{ value: 521, label: 'Nocaima' },
	{ value: 522, label: 'Venecia' },
	{ value: 523, label: 'Pacho' },
	{ value: 524, label: 'Paime' },
	{ value: 525, label: 'Pandi' },
	{ value: 526, label: 'Paratebueno' },
	{ value: 527, label: 'Pasca' },
	{ value: 528, label: 'Puerto Salgar ' },
	{ value: 529, label: 'Pulí' },
	{ value: 530, label: 'Quebradanegra' },
	{ value: 531, label: 'Quetame' },
	{ value: 532, label: 'Quipile' },
	{ value: 533, label: 'Apulo' },
	{ value: 534, label: 'Ricaurte' },
	{ value: 535, label: 'San Antonio Del Tequendama' },
	{ value: 536, label: 'San Bernardo ' },
	{ value: 537, label: 'San Cayetano ' },
	{ value: 538, label: 'San Francisco ' },
	{ value: 539, label: 'San Juan De Rioseco' },
	{ value: 540, label: 'Sasaima' },
	{ value: 541, label: 'Sesquilé' },
	{ value: 542, label: 'Sibaté' },
	{ value: 543, label: 'Silvania' },
	{ value: 544, label: 'Simijaca' },
	{ value: 545, label: 'Soacha' },
	{ value: 546, label: 'Sopó' },
	{ value: 547, label: 'Subachoque' },
	{ value: 548, label: 'Suesca' },
	{ value: 549, label: 'Supatá' },
	{ value: 550, label: 'Susa' },
	{ value: 551, label: 'Sutatausa' },
	{ value: 552, label: 'Tabio' },
	{ value: 553, label: 'Tausa' },
	{ value: 554, label: 'Tena' },
	{ value: 555, label: 'Tenjo' },
	{ value: 556, label: 'Tibacuy' },
	{ value: 557, label: 'Tibirita' },
	{ value: 558, label: 'Tocaima' },
	{ value: 559, label: 'Tocancipá' },
	{ value: 560, label: 'Topaipí' },
	{ value: 561, label: 'Ubalá' },
	{ value: 562, label: 'Ubaque' },
	{ value: 563, label: 'Villa De San Diego De Ubaté' },
	{ value: 564, label: 'Une' },
	{ value: 565, label: 'Útica' },
	{ value: 566, label: 'Vergara' },
	{ value: 567, label: 'Vianí' },
	{ value: 568, label: 'Villagómez' },
	{ value: 569, label: 'Villapinzón' },
	{ value: 570, label: 'Villeta' },
	{ value: 571, label: 'Viotá' },
	{ value: 572, label: 'Yacopí' },
	{ value: 573, label: 'Zipacón' },
	{ value: 574, label: 'Zipaquirá' },
	{ value: 575, label: 'Quibdó' },
	{ value: 576, label: 'Acandí' },
	{ value: 577, label: 'Alto Baudó ' },
	{ value: 578, label: 'Atrato' },
	{ value: 579, label: 'Bagadó' },
	{ value: 580, label: 'Bahía Solano ' },
	{ value: 581, label: 'Bajo Baudó ' },
	{ value: 582, label: 'Bojayá' },
	{ value: 583, label: 'El Cantón Del San Pablo ' },
	{ value: 584, label: 'Carmen Del Darién' },
	{ value: 585, label: 'Cértegui' },
	{ value: 586, label: 'Condoto' },
	{ value: 587, label: 'El Carmen De Atrato' },
	{ value: 588, label: 'El Litoral Del San Juan ' },
	{ value: 589, label: 'Istmina' },
	{ value: 590, label: 'Juradó' },
	{ value: 591, label: 'Lloró' },
	{ value: 592, label: 'Medio Atrato ' },
	{ value: 593, label: 'Medio Baudó ' },
	{ value: 594, label: 'Medio San Juan' },
	{ value: 595, label: 'Nóvita' },
	{ value: 596, label: 'Nuquí' },
	{ value: 597, label: 'Río Iró ' },
	{ value: 598, label: 'Río Quito ' },
	{ value: 599, label: 'Riosucio' },
	{ value: 600, label: 'San José Del Palmar' },
	{ value: 601, label: 'Sipí' },
	{ value: 602, label: 'Tadó' },
	{ value: 603, label: 'Unguía' },
	{ value: 604, label: 'Unión Panamericana ' },
	{ value: 605, label: 'Neiva' },
	{ value: 606, label: 'Acevedo' },
	{ value: 607, label: 'Agrado' },
	{ value: 608, label: 'Aipe' },
	{ value: 609, label: 'Algeciras' },
	{ value: 610, label: 'Altamira' },
	{ value: 611, label: 'Baraya' },
	{ value: 612, label: 'Campoalegre' },
	{ value: 613, label: 'Colombia' },
	{ value: 614, label: 'Elías' },
	{ value: 615, label: 'Garzón' },
	{ value: 616, label: 'Gigante' },
	{ value: 617, label: 'Guadalupe' },
	{ value: 618, label: 'Hobo' },
	{ value: 619, label: 'Íquira' },
	{ value: 620, label: 'Isnos' },
	{ value: 621, label: 'La Argentina ' },
	{ value: 622, label: 'La Plata ' },
	{ value: 623, label: 'Nátaga' },
	{ value: 624, label: 'Oporapa' },
	{ value: 625, label: 'Paicol' },
	{ value: 626, label: 'Palermo' },
	{ value: 627, label: 'Palestina' },
	{ value: 628, label: 'Pital' },
	{ value: 629, label: 'Pitalito' },
	{ value: 630, label: 'Rivera' },
	{ value: 631, label: 'Saladoblanco' },
	{ value: 632, label: 'San Agustín ' },
	{ value: 633, label: 'Santa María ' },
	{ value: 634, label: 'Suaza' },
	{ value: 635, label: 'Tarqui' },
	{ value: 636, label: 'Tesalia' },
	{ value: 637, label: 'Tello' },
	{ value: 638, label: 'Teruel' },
	{ value: 639, label: 'Timaná' },
	{ value: 640, label: 'Villavieja' },
	{ value: 641, label: 'Yaguará' },
	{ value: 642, label: 'Riohacha' },
	{ value: 643, label: 'Albania' },
	{ value: 644, label: 'Barrancas' },
	{ value: 645, label: 'Dibulla' },
	{ value: 646, label: 'Distracción' },
	{ value: 647, label: 'El Molino ' },
	{ value: 648, label: 'Fonseca' },
	{ value: 649, label: 'Hatonuevo' },
	{ value: 650, label: 'La Jagua Del Pilar' },
	{ value: 651, label: 'Maicao' },
	{ value: 652, label: 'Manaure' },
	{ value: 653, label: 'San Juan Del Cesar' },
	{ value: 654, label: 'Uribia' },
	{ value: 655, label: 'Urumita' },
	{ value: 656, label: 'Villanueva' },
	{ value: 657, label: 'Santa Marta ' },
	{ value: 658, label: 'Algarrobo' },
	{ value: 659, label: 'Aracataca' },
	{ value: 660, label: 'Ariguaní' },
	{ value: 661, label: 'Cerro De San Antonio' },
	{ value: 662, label: 'Chivolo' },
	{ value: 663, label: 'Ciénaga' },
	{ value: 664, label: 'Concordia' },
	{ value: 665, label: 'El Banco ' },
	{ value: 666, label: 'El Piñón ' },
	{ value: 667, label: 'El Retén ' },
	{ value: 668, label: 'Fundación' },
	{ value: 669, label: 'Guamal' },
	{ value: 670, label: 'Nueva Granada ' },
	{ value: 671, label: 'Pedraza' },
	{ value: 672, label: 'Pijiño Del Carmen' },
	{ value: 673, label: 'Pivijay' },
	{ value: 674, label: 'Plato' },
	{ value: 675, label: 'Puebloviejo' },
	{ value: 676, label: 'Remolino' },
	{ value: 677, label: 'Sabanas De San Ángel' },
	{ value: 678, label: 'Salamina' },
	{ value: 679, label: 'San Sebastián De Buenavista' },
	{ value: 680, label: 'San Zenón ' },
	{ value: 681, label: 'Santa Ana ' },
	{ value: 682, label: 'Santa Bárbara De Pinto' },
	{ value: 683, label: 'Sitionuevo' },
	{ value: 684, label: 'Tenerife' },
	{ value: 685, label: 'Zapayán' },
	{ value: 686, label: 'Zona Bananera ' },
	{ value: 687, label: 'Villavicencio' },
	{ value: 688, label: 'Acacías' },
	{ value: 689, label: 'Barranca De Upía' },
	{ value: 690, label: 'Cabuyaro' },
	{ value: 691, label: 'Castilla La Nueva' },
	{ value: 692, label: 'Cubarral' },
	{ value: 693, label: 'Cumaral' },
	{ value: 694, label: 'El Calvario ' },
	{ value: 695, label: 'El Castillo ' },
	{ value: 696, label: 'El Dorado ' },
	{ value: 697, label: 'Fuente De Oro' },
	{ value: 698, label: 'Granada' },
	{ value: 699, label: 'Guamal' },
	{ value: 700, label: 'Mapiripán' },
	{ value: 701, label: 'Mesetas' },
	{ value: 702, label: 'La Macarena ' },
	{ value: 703, label: 'Uribe' },
	{ value: 704, label: 'Lejanías' },
	{ value: 705, label: 'Puerto Concordia ' },
	{ value: 706, label: 'Puerto Gaitán ' },
	{ value: 707, label: 'Puerto López ' },
	{ value: 708, label: 'Puerto Lleras ' },
	{ value: 709, label: 'Puerto Rico ' },
	{ value: 710, label: 'Restrepo' },
	{ value: 711, label: 'San Carlos De Guaroa' },
	{ value: 712, label: 'San Juan De Arama' },
	{ value: 713, label: 'San Juanito ' },
	{ value: 714, label: 'San Martín ' },
	{ value: 715, label: 'Vistahermosa' },
	{ value: 716, label: 'Pasto' },
	{ value: 717, label: 'Albán' },
	{ value: 718, label: 'Aldana' },
	{ value: 719, label: 'Ancuyá' },
	{ value: 720, label: 'Arboleda' },
	{ value: 721, label: 'Barbacoas' },
	{ value: 722, label: 'Belén' },
	{ value: 723, label: 'Buesaco' },
	{ value: 724, label: 'Colón' },
	{ value: 725, label: 'Consacá' },
	{ value: 726, label: 'Contadero' },
	{ value: 727, label: 'Córdoba' },
	{ value: 728, label: 'Cuaspúd' },
	{ value: 729, label: 'Cumbal' },
	{ value: 730, label: 'Cumbitara' },
	{ value: 731, label: 'Chachagüí' },
	{ value: 732, label: 'El Charco ' },
	{ value: 733, label: 'El Peñol ' },
	{ value: 734, label: 'El Rosario ' },
	{ value: 735, label: 'El Tablón De Gómez' },
	{ value: 736, label: 'El Tambo ' },
	{ value: 737, label: 'Funes' },
	{ value: 738, label: 'Guachucal' },
	{ value: 739, label: 'Guaitarilla' },
	{ value: 740, label: 'Gualmatán' },
	{ value: 741, label: 'Iles' },
	{ value: 742, label: 'Imués' },
	{ value: 743, label: 'Ipiales' },
	{ value: 744, label: 'La Cruz ' },
	{ value: 745, label: 'La Florida ' },
	{ value: 746, label: 'La Llanada ' },
	{ value: 747, label: 'La Tola ' },
	{ value: 748, label: 'La Unión ' },
	{ value: 749, label: 'Leiva' },
	{ value: 750, label: 'Linares' },
	{ value: 751, label: 'Los Andes ' },
	{ value: 752, label: 'Magüí' },
	{ value: 753, label: 'Mallama' },
	{ value: 754, label: 'Mosquera' },
	{ value: 755, label: 'Nariño' },
	{ value: 756, label: 'Olaya Herrera ' },
	{ value: 757, label: 'Ospina' },
	{ value: 758, label: 'Francisco Pizarro ' },
	{ value: 759, label: 'Policarpa' },
	{ value: 760, label: 'Potosí' },
	{ value: 761, label: 'Providencia' },
	{ value: 762, label: 'Puerres' },
	{ value: 763, label: 'Pupiales' },
	{ value: 764, label: 'Ricaurte' },
	{ value: 765, label: 'Roberto Payán ' },
	{ value: 766, label: 'Samaniego' },
	{ value: 767, label: 'Sandoná' },
	{ value: 768, label: 'San Bernardo ' },
	{ value: 769, label: 'San Lorenzo ' },
	{ value: 770, label: 'San Pablo ' },
	{ value: 771, label: 'San Pedro De Cartago' },
	{ value: 772, label: 'Santa Bárbara ' },
	{ value: 773, label: 'Santacruz' },
	{ value: 774, label: 'Sapuyes' },
	{ value: 775, label: 'Taminango' },
	{ value: 776, label: 'Tangua' },
	{ value: 777, label: 'San Andrés De Tumaco' },
	{ value: 778, label: 'Túquerres' },
	{ value: 779, label: 'Yacuanquer' },
	{ value: 780, label: 'San José De Cúcuta' },
	{ value: 781, label: 'Ábrego' },
	{ value: 782, label: 'Arboledas' },
	{ value: 783, label: 'Bochalema' },
	{ value: 784, label: 'Bucarasica' },
	{ value: 785, label: 'Cácota' },
	{ value: 786, label: 'Cáchira' },
	{ value: 787, label: 'Chinácota' },
	{ value: 788, label: 'Chitagá' },
	{ value: 789, label: 'Convención' },
	{ value: 790, label: 'Cucutilla' },
	{ value: 791, label: 'Durania' },
	{ value: 792, label: 'El Carmen ' },
	{ value: 793, label: 'El Tarra ' },
	{ value: 794, label: 'El Zulia ' },
	{ value: 795, label: 'Gramalote' },
	{ value: 796, label: 'Hacarí' },
	{ value: 797, label: 'Herrán' },
	{ value: 798, label: 'Labateca' },
	{ value: 799, label: 'La Esperanza ' },
	{ value: 800, label: 'La Playa ' },
	{ value: 801, label: 'Los Patios ' },
	{ value: 802, label: 'Lourdes' },
	{ value: 803, label: 'Mutiscua' },
	{ value: 804, label: 'Ocaña' },
	{ value: 805, label: 'Pamplona' },
	{ value: 806, label: 'Pamplonita' },
	{ value: 807, label: 'Puerto Santander ' },
	{ value: 808, label: 'Ragonvalia' },
	{ value: 809, label: 'Salazar' },
	{ value: 810, label: 'San Calixto ' },
	{ value: 811, label: 'San Cayetano ' },
	{ value: 812, label: 'Santiago' },
	{ value: 813, label: 'Sardinata' },
	{ value: 814, label: 'Silos' },
	{ value: 815, label: 'Teorama' },
	{ value: 816, label: 'Tibú' },
	{ value: 817, label: 'Toledo' },
	{ value: 818, label: 'Villa Caro ' },
	{ value: 819, label: 'Villa Del Rosario' },
	{ value: 820, label: 'Armenia' },
	{ value: 821, label: 'Buenavista' },
	{ value: 822, label: 'Calarcá' },
	{ value: 823, label: 'Circasia' },
	{ value: 824, label: 'Córdoba' },
	{ value: 825, label: 'Filandia' },
	{ value: 826, label: 'Génova' },
	{ value: 827, label: 'La Tebaida ' },
	{ value: 828, label: 'Montenegro' },
	{ value: 829, label: 'Pijao' },
	{ value: 830, label: 'Quimbaya' },
	{ value: 831, label: 'Salento' },
	{ value: 832, label: 'Pereira' },
	{ value: 833, label: 'Apía' },
	{ value: 834, label: 'Balboa' },
	{ value: 835, label: 'Belén De Umbría' },
	{ value: 836, label: 'Dosquebradas' },
	{ value: 837, label: 'Guática' },
	{ value: 838, label: 'La Celia ' },
	{ value: 839, label: 'La Virginia ' },
	{ value: 840, label: 'Marsella' },
	{ value: 841, label: 'Mistrató' },
	{ value: 842, label: 'Pueblo Rico ' },
	{ value: 843, label: 'Quinchía' },
	{ value: 844, label: 'Santa Rosa De Cabal' },
	{ value: 845, label: 'Santuario' },
	{ value: 846, label: 'Bucaramanga' },
	{ value: 847, label: 'Aguada' },
	{ value: 848, label: 'Albania' },
	{ value: 849, label: 'Aratoca' },
	{ value: 850, label: 'Barbosa' },
	{ value: 851, label: 'Barichara' },
	{ value: 852, label: 'Barrancabermeja' },
	{ value: 853, label: 'Betulia' },
	{ value: 854, label: 'Bolívar' },
	{ value: 855, label: 'Cabrera' },
	{ value: 856, label: 'California' },
	{ value: 857, label: 'Capitanejo' },
	{ value: 858, label: 'Carcasí' },
	{ value: 859, label: 'Cepitá' },
	{ value: 860, label: 'Cerrito' },
	{ value: 861, label: 'Charalá' },
	{ value: 862, label: 'Charta' },
	{ value: 863, label: 'Chima' },
	{ value: 864, label: 'Chipatá' },
	{ value: 865, label: 'Cimitarra' },
	{ value: 866, label: 'Concepción' },
	{ value: 867, label: 'Confines' },
	{ value: 868, label: 'Contratación' },
	{ value: 869, label: 'Coromoro' },
	{ value: 870, label: 'Curití' },
	{ value: 871, label: 'El Carmen De Chucurí' },
	{ value: 872, label: 'El Guacamayo ' },
	{ value: 873, label: 'El Peñón ' },
	{ value: 874, label: 'El Playón ' },
	{ value: 875, label: 'Encino' },
	{ value: 876, label: 'Enciso' },
	{ value: 877, label: 'Florián' },
	{ value: 878, label: 'Floridablanca' },
	{ value: 879, label: 'Galán' },
	{ value: 880, label: 'Gámbita' },
	{ value: 881, label: 'Girón' },
	{ value: 882, label: 'Guaca' },
	{ value: 883, label: 'Guadalupe' },
	{ value: 884, label: 'Guapotá' },
	{ value: 885, label: 'Guavatá' },
	{ value: 886, label: 'Güepsa' },
	{ value: 887, label: 'Hato' },
	{ value: 888, label: 'Jesús María ' },
	{ value: 889, label: 'Jordán' },
	{ value: 890, label: 'La Belleza ' },
	{ value: 891, label: 'Landázuri' },
	{ value: 892, label: 'La Paz ' },
	{ value: 893, label: 'Lebrija' },
	{ value: 894, label: 'Los Santos ' },
	{ value: 895, label: 'Macaravita' },
	{ value: 896, label: 'Málaga' },
	{ value: 897, label: 'Matanza' },
	{ value: 898, label: 'Mogotes' },
	{ value: 899, label: 'Molagavita' },
	{ value: 900, label: 'Ocamonte' },
	{ value: 901, label: 'Oiba' },
	{ value: 902, label: 'Onzaga' },
	{ value: 903, label: 'Palmar' },
	{ value: 904, label: 'Palmas Del Socorro' },
	{ value: 905, label: 'Páramo' },
	{ value: 906, label: 'Piedecuesta' },
	{ value: 907, label: 'Pinchote' },
	{ value: 908, label: 'Puente Nacional ' },
	{ value: 909, label: 'Puerto Parra ' },
	{ value: 910, label: 'Puerto Wilches ' },
	{ value: 911, label: 'Rionegro' },
	{ value: 912, label: 'Sabana De Torres' },
	{ value: 913, label: 'San Andrés ' },
	{ value: 914, label: 'San Benito ' },
	{ value: 915, label: 'San Gil ' },
	{ value: 916, label: 'San Joaquín ' },
	{ value: 917, label: 'San José De Miranda' },
	{ value: 918, label: 'San Miguel ' },
	{ value: 919, label: 'San Vicente De Chucurí' },
	{ value: 920, label: 'Santa Bárbara ' },
	{ value: 921, label: 'Santa Helena Del Opón' },
	{ value: 922, label: 'Simacota' },
	{ value: 923, label: 'Socorro' },
	{ value: 924, label: 'Suaita' },
	{ value: 925, label: 'Sucre' },
	{ value: 926, label: 'Suratá' },
	{ value: 927, label: 'Tona' },
	{ value: 928, label: 'Valle De San José' },
	{ value: 929, label: 'Vélez' },
	{ value: 930, label: 'Vetas' },
	{ value: 931, label: 'Villanueva' },
	{ value: 932, label: 'Zapatoca' },
	{ value: 933, label: 'Sincelejo' },
	{ value: 934, label: 'Buenavista' },
	{ value: 935, label: 'Caimito' },
	{ value: 936, label: 'Colosó' },
	{ value: 937, label: 'Corozal' },
	{ value: 938, label: 'Coveñas' },
	{ value: 939, label: 'Chalán' },
	{ value: 940, label: 'El Roble ' },
	{ value: 941, label: 'Galeras' },
	{ value: 942, label: 'Guaranda' },
	{ value: 943, label: 'La Unión ' },
	{ value: 944, label: 'Los Palmitos ' },
	{ value: 945, label: 'Majagual' },
	{ value: 946, label: 'Morroa' },
	{ value: 947, label: 'Ovejas' },
	{ value: 948, label: 'Palmito' },
	{ value: 949, label: 'Sampués' },
	{ value: 950, label: 'San Benito Abad' },
	{ value: 951, label: 'San Juan De Betulia' },
	{ value: 952, label: 'San Marcos ' },
	{ value: 953, label: 'San Onofre ' },
	{ value: 954, label: 'San Pedro ' },
	{ value: 955, label: 'San Luis De Sincé' },
	{ value: 956, label: 'Sucre' },
	{ value: 957, label: 'Santiago De Tolú' },
	{ value: 958, label: 'Tolú Viejo ' },
	{ value: 959, label: 'Ibagué' },
	{ value: 960, label: 'Alpujarra' },
	{ value: 961, label: 'Alvarado' },
	{ value: 962, label: 'Ambalema' },
	{ value: 963, label: 'Anzoátegui' },
	{ value: 964, label: 'Armero' },
	{ value: 965, label: 'Ataco' },
	{ value: 966, label: 'Cajamarca' },
	{ value: 967, label: 'Carmen De Apicalá' },
	{ value: 968, label: 'Casabianca' },
	{ value: 969, label: 'Chaparral' },
	{ value: 970, label: 'Coello' },
	{ value: 971, label: 'Coyaima' },
	{ value: 972, label: 'Cunday' },
	{ value: 973, label: 'Dolores' },
	{ value: 974, label: 'Espinal' },
	{ value: 975, label: 'Falan' },
	{ value: 976, label: 'Flandes' },
	{ value: 977, label: 'Fresno' },
	{ value: 978, label: 'Guamo' },
	{ value: 979, label: 'Herveo' },
	{ value: 980, label: 'Honda' },
	{ value: 981, label: 'Icononzo' },
	{ value: 982, label: 'Lérida' },
	{ value: 983, label: 'Líbano' },
	{ value: 984, label: 'San Sebastián De Mariquita' },
	{ value: 985, label: 'Melgar' },
	{ value: 986, label: 'Murillo' },
	{ value: 987, label: 'Natagaima' },
	{ value: 988, label: 'Ortega' },
	{ value: 989, label: 'Palocabildo' },
	{ value: 990, label: 'Piedras' },
	{ value: 991, label: 'Planadas' },
	{ value: 992, label: 'Prado' },
	{ value: 993, label: 'Purificación' },
	{ value: 994, label: 'Rioblanco' },
	{ value: 995, label: 'Roncesvalles' },
	{ value: 996, label: 'Rovira' },
	{ value: 997, label: 'Saldaña' },
	{ value: 998, label: 'San Antonio ' },
	{ value: 999, label: 'San Luis ' },
	{ value: 1000, label: 'Santa Isabel ' },
	{ value: 1001, label: 'Suárez' },
	{ value: 1002, label: 'Valle De San Juan' },
	{ value: 1003, label: 'Venadillo' },
	{ value: 1004, label: 'Villahermosa' },
	{ value: 1005, label: 'Villarrica' },
	{ value: 1006, label: 'Cali' },
	{ value: 1007, label: 'Alcalá' },
	{ value: 1008, label: 'Andalucía' },
	{ value: 1009, label: 'Ansermanuevo' },
	{ value: 1010, label: 'Argelia' },
	{ value: 1011, label: 'Bolívar' },
	{ value: 1012, label: 'Buenaventura' },
	{ value: 1013, label: 'Guadalajara De Buga' },
	{ value: 1014, label: 'Bugalagrande' },
	{ value: 1015, label: 'Caicedonia' },
	{ value: 1016, label: 'Calima' },
	{ value: 1017, label: 'Candelaria' },
	{ value: 1018, label: 'Cartago' },
	{ value: 1019, label: 'Dagua' },
	{ value: 1020, label: 'El Águila ' },
	{ value: 1021, label: 'El Cairo ' },
	{ value: 1022, label: 'El Cerrito ' },
	{ value: 1023, label: 'El Dovio ' },
	{ value: 1024, label: 'Florida' },
	{ value: 1025, label: 'Ginebra' },
	{ value: 1026, label: 'Guacarí' },
	{ value: 1027, label: 'Jamundí' },
	{ value: 1028, label: 'La Cumbre ' },
	{ value: 1029, label: 'La Unión ' },
	{ value: 1030, label: 'La Victoria ' },
	{ value: 1031, label: 'Obando' },
	{ value: 1032, label: 'Palmira' },
	{ value: 1033, label: 'Pradera' },
	{ value: 1034, label: 'Restrepo' },
	{ value: 1035, label: 'Riofrío' },
	{ value: 1036, label: 'Roldanillo' },
	{ value: 1037, label: 'San Pedro ' },
	{ value: 1038, label: 'Sevilla' },
	{ value: 1039, label: 'Toro' },
	{ value: 1040, label: 'Trujillo' },
	{ value: 1041, label: 'Tuluá' },
	{ value: 1042, label: 'Ulloa' },
	{ value: 1043, label: 'Versalles' },
	{ value: 1044, label: 'Vijes' },
	{ value: 1045, label: 'Yotoco' },
	{ value: 1046, label: 'Yumbo' },
	{ value: 1047, label: 'Zarzal' },
	{ value: 1048, label: 'Arauca' },
	{ value: 1049, label: 'Arauquita' },
	{ value: 1050, label: 'Cravo Norte ' },
	{ value: 1051, label: 'Fortul' },
	{ value: 1052, label: 'Puerto Rondón ' },
	{ value: 1053, label: 'Saravena' },
	{ value: 1054, label: 'Tame' },
	{ value: 1055, label: 'Yopal' },
	{ value: 1056, label: 'Aguazul' },
	{ value: 1057, label: 'Chámeza' },
	{ value: 1058, label: 'Hato Corozal ' },
	{ value: 1059, label: 'La Salina ' },
	{ value: 1060, label: 'Maní' },
	{ value: 1061, label: 'Monterrey' },
	{ value: 1062, label: 'Nunchía' },
	{ value: 1063, label: 'Orocué' },
	{ value: 1064, label: 'Paz De Ariporo' },
	{ value: 1065, label: 'Pore' },
	{ value: 1066, label: 'Recetor' },
	{ value: 1067, label: 'Sabanalarga' },
	{ value: 1068, label: 'Sácama' },
	{ value: 1069, label: 'San Luis De Palenque' },
	{ value: 1070, label: 'Támara' },
	{ value: 1071, label: 'Tauramena' },
	{ value: 1072, label: 'Trinidad' },
	{ value: 1073, label: 'Villanueva' },
	{ value: 1074, label: 'Mocoa' },
	{ value: 1075, label: 'Colón' },
	{ value: 1076, label: 'Orito' },
	{ value: 1077, label: 'Puerto Asís ' },
	{ value: 1078, label: 'Puerto Caicedo ' },
	{ value: 1079, label: 'Puerto Guzmán ' },
	{ value: 1080, label: 'Puerto Leguízamo ' },
	{ value: 1081, label: 'Sibundoy' },
	{ value: 1082, label: 'San Francisco ' },
	{ value: 1083, label: 'San Miguel ' },
	{ value: 1084, label: 'Santiago' },
	{ value: 1085, label: 'Valle Del Guamuez' },
	{ value: 1086, label: 'Villagarzón' },
	{ value: 1087, label: 'San Andrés ' },
	{ value: 1088, label: 'Providencia' },
	{ value: 1089, label: 'Leticia' },
	{ value: 1090, label: 'El Encanto ' },
	{ value: 1091, label: 'La Chorrera ' },
	{ value: 1092, label: 'La Pedrera ' },
	{ value: 1093, label: 'La Victoria ' },
	{ value: 1094, label: 'Mirití - Paraná' },
	{ value: 1095, label: 'Puerto Alegría ' },
	{ value: 1096, label: 'Puerto Arica ' },
	{ value: 1097, label: 'Puerto Nariño ' },
	{ value: 1098, label: 'Puerto Santander ' },
	{ value: 1099, label: 'Tarapacá' },
	{ value: 1100, label: 'Inírida' },
	{ value: 1101, label: 'Barranco Minas ' },
	{ value: 1102, label: 'Mapiripana' },
	{ value: 1103, label: 'San Felipe ' },
	{ value: 1104, label: 'Puerto Colombia ' },
	{ value: 1105, label: 'La Guadalupe ' },
	{ value: 1106, label: 'Cacahual' },
	{ value: 1107, label: 'Pana Pana ' },
	{ value: 1108, label: 'Morichal' },
	{ value: 1109, label: 'San José Del Guaviare' },
	{ value: 1110, label: 'Calamar' },
	{ value: 1111, label: 'El Retorno ' },
	{ value: 1112, label: 'Miraflores' },
	{ value: 1113, label: 'Mitú' },
	{ value: 1114, label: 'Carurú' },
	{ value: 1115, label: 'Pacoa' },
	{ value: 1116, label: 'Taraira' },
	{ value: 1117, label: 'Papunahua' },
	{ value: 1118, label: 'Yavaraté' },
	{ value: 1119, label: 'Puerto Carreño ' },
	{ value: 1120, label: 'La Primavera ' },
	{ value: 1121, label: 'Santa Rosalía ' },
	{ value: 1122, label: 'Cumaribo' },
] satisfies Array<{ value: number; label: string }>;

export const municipalitiesValues = municipalities.map(m => ({
	value: m.label,
	label: m.label,
}));

export const typeCompanies = [
	{ value: 'normal', label: 'Comercio' },
	{ value: 'pharmacy', label: 'Manejo de medicamentos' },
] satisfies Array<{
	value: keyof typeof VillingOrganizationType;
	label: string;
}>;

type Retention = { label: string; value: number };
export const retentions: Array<Retention> = [
	{ value: 0, label: 'No aplica' },
	{
		value: 3,
		label:
			'3.000% Sobre base - Cuota de Fomento Cacaotero - Cuota de Fomento - Base mínima: $0',
	},
	{
		value: 1,
		label:
			'1.000% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 10 X MIL - Base mínima: $0',
	},
	{
		value: 0.9,
		label:
			'0.900% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 9 X MIL - Base mínima: $0',
	},
	{
		value: 0.8,
		label:
			'0.800% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 8 X MIL - Base mínima: $0',
	},
	{
		value: 0.7,
		label:
			'0.700% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 7 X MIL - Base mínima: $0',
	},
	{
		value: 0.6,
		label:
			'0.600% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 6 X MIL - Base mínima: $0',
	},
	{
		value: 0.5,
		label:
			'0.500% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 5 X MIL - Base mínima: $0',
	},
	{
		value: 0.4,
		label:
			'0.400% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 4 X MIL - Base mínima: $0',
	},
	{
		value: 0.3,
		label:
			'0.300% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 3 X MIL - Base mínima: $0',
	},
	{
		value: 0.2,
		label:
			'0.200% Sobre base - Impuesto de Industria y Comercio ICA - RETEICA 2 X MIL - Base mínima: $0',
	},
	{
		value: 33,
		label:
			'33.000% Sobre base - Retención por pagos al exterior - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 20,
		label:
			'20.000% Sobre base - Retención por pagos al exterior - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 15,
		label:
			'15.000% Sobre base - Retención por pagos al exterior - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 5,
		label:
			'5.000% Sobre base - Retención por pagos al exterior - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 1,
		label:
			'1.000% Sobre base - Retención por pagos al exterior - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 2,
		label:
			'2.000% Sobre base - Contratos de construcción y urbanización. - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 3,
		label:
			'3.000% Sobre base - Retención en colocación independiente de juegos de suerte y azar - RETE FUENTE - Base mínima: $212,000',
	},
	{
		value: 20,
		label:
			'20.000% Sobre base - Loterías, rifas, apuestas y similares - RETE FUENTE - Base mínima: $2,036,000',
	},
	{
		value: 4,
		label:
			'4.000% Sobre base - Rendimientos financieros provenientes de títulos de renta fija - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 3.5,
		label:
			'3.500% Sobre base - Otros ingresos tributarios (no declarantes) - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 2.5,
		label:
			'2.500% Sobre base - Otros ingresos tributarios (declarantes) - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 3.5,
		label:
			'3.500% Sobre base - Por emolumentos eclesiásticos (no declarantes) - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 4,
		label:
			'4.000% Sobre base - Por emolumentos eclesiásticos (declarantes) - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 2.5,
		label:
			'2.500% Sobre base - Compras de bienes raíces cuya destinación y uso sea distinto a viviend - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 2.5,
		label:
			'2.500% Sobre base - Compras de bienes raíces cuya destinación y uso sea vivienda de habita - RETE FUENTE - Base mínima: $848,240,000',
	},
	{
		value: 1,
		label:
			'1.000% Sobre base - Compras de bienes raíces cuya destinación y uso sea vivienda de habita - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 1,
		label:
			'1.000% Sobre base - Compras de vehículos - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 1,
		label:
			'1.000% Sobre base - Enajenación de activos fijos de personas naturales (notarías y tránsit - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 0.5,
		label:
			'0.500% Sobre base - Compras de café pergamino o cereza - RETE FUENTE - Base mínima: $6,786,000',
	},
	{
		value: 3.5,
		label:
			'3.500% Sobre base - Compras de bienes o productos agrícolas o pecuarios con procesamiento - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 2.5,
		label:
			'2.500% Sobre base - Compras de bienes o productos agrícolas o pecuarios con procesamiento - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 1.5,
		label:
			'1.500% Sobre base - Compras de bienes o productos agrícolas o pecuarios sin procesamiento - RETE FUENTE - Base mínima: $3,902,000',
	},
	{
		value: 1.5,
		label:
			'1.500% Sobre base - Bienes o productos agrícolas o pecuarios - RETE FUENTE - Base mínima: $3,902,000',
	},
	{
		value: 7,
		label:
			'7.000% Sobre base - Intereses o rendimientos financieros en general - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 3.5,
		label:
			'3.500% Sobre base - Servicios de licenciamiento o derecho de uso de software - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 10,
		label:
			'10.000% Sobre base - Honorarios y comisiones (no declarantes) - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 11,
		label:
			'11.000% Sobre base - Honorarios y comisiones (personas naturales con contrato o con pagos q - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 11,
		label:
			'11.000% Sobre base - Honorarios y comisiones (personas jurídicas) - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 3.5,
		label:
			'3.500% Sobre base - Arrendamiento de bienes inmuebles - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 4,
		label:
			'4.000% Sobre base - Arrendamiento de bienes muebles - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 3.5,
		label:
			'3.500% Sobre base - Servicios de hoteles y restaurantes - RETE FUENTE - Base mínima: $170,000',
	},
	{
		value: 2,
		label:
			'2.000% Sobre base - Servicios integrales de salud prestados por IPS - RETE FUENTE - Base mínima: $170,000',
	},
	{
		value: 2,
		label:
			'2.000% Sobre base - Servicios prestados por empresas de vigilancia y aseo - RETE FUENTE - Base mínima: $170,000',
	},
	{
		value: 1,
		label:
			'1.000% Sobre base - Servicios prestados por empresas de servicios temporales - RETE FUENTE - Base mínima: $170,000',
	},
	{
		value: 1,
		label:
			'1.000% Sobre base - Transporte nacional de pasajeros por vía aérea o marítima - RETE FUENTE - Base mínima: $170,000',
	},
	{
		value: 3.5,
		label:
			'3.500% Sobre base - Transporte nacional de pasajeros por vía terrestre - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 1,
		label:
			'1.000% Sobre base - Transporte de carga - RETE FUENTE - Base mínima: $170,000',
	},
	{
		value: 6,
		label:
			'6.000% Sobre base - Servicios generales (no declarantes) - RETE FUENTE - Base mínima: $170,000',
	},
	{
		value: 4,
		label:
			'4.000% Sobre base - Servicios generales (declarantes) - RETE FUENTE - Base mínima: $170,000',
	},
	{
		value: 0.1,
		label:
			'0.100% Sobre base - Compras de combustibles derivados del petróleo - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 1.5,
		label:
			'1.500% Sobre base - Compras con tarjeta débito o crédito - RETE FUENTE - Base mínima: $0',
	},
	{
		value: 3.5,
		label:
			'3.500% Sobre base - Compras generales (no declarantes) - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 2.5,
		label:
			'2.500% Sobre base - Compras generales (declarantes) - RETE FUENTE - Base mínima: $1,145,000',
	},
	{
		value: 15,
		label:
			'15.000% Sobre impuestos de tipo IVA - Retención en el IVA - RETEIVA - Base mínima: $0',
	},
];

const workers = [
	'Dependiente',
	'Servicio domestico',
	'Madre comunitaria',
	'Aprendices del Sena en etapa lectiva',
	'Funcionarios públicos sin tope máximo de ibc',
	'Aprendices del SENA en etapa productiva',
	'Estudiantes de postgrado en salud',
	'Profesor de establecimiento particular',
	'Estudiantes aportes solo riesgos laborales',
	'Dependiente entidades o universidades públicas con régimen especial en salud',
	'Cooperados o pre cooperativas de trabajo asociado',
	'Trabajador dependiente de entidad beneficiaria del sistema general de participaciones - aportes patronales',
	'Trabajador de tiempo parcial',
	'Pre pensionado de entidad en liquidación.',
	'Pre pensionado con aporte voluntario a salud',
	'Estudiantes de prácticas laborales en el sector público',
];
export const typeWorkers = workers.map(worker => ({
	value: worker,
	label: worker,
}));
export const typeWorkersMapper = getMapper(workers);

const contracts = [
	'Termino Fijo',
	'Término Indefinido',
	'Obra o Labor',
	'Aprendizaje',
	'Prácticas o Pasantías',
];
export const typeContracts = contracts.map(contract => ({
	value: contract,
	label: contract,
}));
export const typeContractsMapper = getMapper(contracts);

const payments = [
	'Instrumento no definido',
	'Crédito ACH',
	'Débito ACH',
	'Reversión débito de demanda AC',
	'Reversión crédito de demanda ACH',
	'Crédito de demanda ACH',
	'Débito de demanda ACH',
	'Clearing Nacional o Regional',
	'Efectivo',
	'Reversión Crédito Ahorro',
	'Reversión Débito Ahorro',
	'Crédito Ahorro',
	'Débito Ahorro',
	'Bookentry Crédito',
	'Bookentry Débito',
	'Desembolso Crédito (CCD)',
	'Desembolso (CCD) débito',
	'Crédito Pago negocio corporativo (CTP)',
	'Cheque',
	'Poyecto bancario',
	'Proyecto bancario certificado',
	'Cheque bancario de gerencia',
	'Nota cambiaria esperando aceptación',
	'Cheque certificado',
	'Cheque Local',
	'Débito Pago Neogcio Corporativo (CTP)',
	'Crédito Negocio Intercambio Corporativo (CTX)',
	'Débito Negocio Intercambio Corporativo (CTX)',
	'Transferencia Crédito',
	'Transferencia Débito',
	'Desembolso Crédito plus (CCD+)',
	'Desembolso Débito plus (CCD+)',
	'Pago y depósito pre acordado (PPD)',
	'Desembolso Crédito (CCD)',
	'Desembolso Débito (CCD)',
	'Pago Negocio Corporativo Ahorros Crédito (CTP)',
	'Pago Negocio Corporativo Ahorros Débito (CTP)',
	'Crédito Intercambio Corporativo (CTX)',
	'Débito Intercambio Corporativo (CTX)',
	'Desembolso Crédito plus (CCD+)',
	'Consiganción bancaria',
	'Desembolso Débito plus (CCD+)',
	'Nota cambiaria',
	'Transferencia Crédito Bancario',
	'Transferencia Débito Interbancario',
	'Transferencia Débito Bancaria',
	'Tarjeta Crédito',
	'Tarjeta Débito',
	'Postgiro',
	'Telex estándar bancario',
	'Pago comercial urgente',
	'Pago Tesorería Urgente',
	'Nota promisoria',
	'Nota promisoria firmada por el acreedor',
	'Nota promisoria firmada por el acreedor, avalada por el banco',
	'Nota promisoria firmada por el acreedor, avalada por un tercero',
	'Nota promisoria firmada pro el banco',
	'Nota promisoria firmada por un banco avalada por otro banco',
	'Nota promisoria firmada',
	'Nota promisoria firmada por un tercero avalada por un banco',
	'Retiro de nota por el por el acreedor',
	'Retiro de nota por el por el acreedor sobre un banco',
	'Retiro de nota por el acreedor, avalada por otro banco',
	'Retiro de nota por el acreedor, sobre un banco avalada por un tercero',
	'Retiro de una nota por el acreedor sobre un tercero',
	'Retiro de una nota por el acreedor sobre un tercero avalada por un banco',
	'Nota bancaria transferible',
	'Cheque local transferible',
	'Giro referenciado',
	'Giro urgente',
	'Giro formato abierto',
	'Método de pago solicitado no usuado',
	'Clearing entre partners',
	'Otro',
	'Bonos',
	'Vales',
	'Pago individual por caso / Conjunto integral de atenciones / Paquete / Canasta.',
	'Pago global prospectivo.',
	'Pago por capitación.',
	'Pago por evento.',
	'Otra modalidad (específica)',
	'Mantener',
	'Cuentas de Ahorro de Tramite Simplificado(CATS)(Nequi, Daviplata, etc)',
];
export const paymentMethods = payments.map(payment => ({
	value: payment,
	label: payment,
}));

export const paymentMethodsMapper = getMapper(payments);

function getMapper(arr: Array<string>): Record<string, number> {
	return arr.reduce(
		(acc, value, index) => ({
			...acc,
			[value]: index + 1,
			[value.toLowerCase()]: index + 1,
		}),
		{},
	);
}

const compensations = [
	'CAJA DE COMPENSACIÓN FAMILIAR CAMACOL COMFAMILIAR CAMACOL',
	'CAJA DE COMPENSACIÓN FAMILIAR COMFENALCO ANTIOQUIA',
	'CAJA DE COMPENSACIÓN FAMILIAR DE ANTIOQUIA COMFAMA',
	'CAJA DE COMPENSACIÓN FAMILIAR CAJACOPI ATLANTICO',
	'CAJA DE COMPENSACIÓN FAMILIAR DE BARRANQUILLA COMBARRANQUILLA',
	'CAJA DE COMPENSACIÓN FAMILIAR COMFAMILIAR DEL ATLANTICO',
	'CAJA DE COMPENSACIÓN FAMILIAR DE FENALCO - ANDI COMFENALCO CARTAGENA',
	'CAJA DE COMPENSACIÓN FAMILIAR DE CARTAGENA',
	'CAJA DE COMPENSACIÓN FAMILIAR DE BOYACA - COMFABOY',
	'CAJA DE COMPENSACIÓN FAMILIAR DE CALDAS',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL CAQUETÁ - COMFACA',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL CAUCA - COMFACAUCA',
	'COMFACESAR',
	'CAJA DE COMPENSACIÓN FAMILIAR DE CORDOBA COMFACOR',
	'CAJA DE COMPENSACIÓN FAMILIAR CAFAM',
	'CAJA COLOMBIANA DE SUBSIDIO FAMILIAR COLSUBSIDIO',
	'CAJA DE COMPENSACIÓN FAMILIAR COMPENSAR',
	'CAJA DE COMPENSACIÓN FAMILIAR DE CUNDINAMARCA - COMFACUNDI',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL CHOCÓ',
	'CAJA DE COMPENSACIÓN FAMILIAR DE LA GUAJIRA',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL HUILA - COMFAMILIAR',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL MAGDALENA',
	'CAJA DE COMPENSACIÓN FAMILIAR REGIONAL DEL META COFREM',
	'CAJA DE COMPENSACIÓN FAMILIAR DE NARIÑO',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO COMFAORIENTE',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL NORTE DE SANTANDER COMFANORTE',
	'CAJA DE COMPENSACIÓN FAMILIAR DE BARRANCABERMEJA CAFABA',
	'CAJA SANTANDEREANA DE SUBSIDIO FAMILIAR CAJASAN',
	'CAJA DE COMPENSACIÓN FAMILIAR COMFENALCO SANTANDER',
	'CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE',
	'CAJA DE COMPENSACIÓN FAMILIAR DE FENALCO COMFENALCO QUINDIO',
	'CAJA DE COMPENSACIÓN FAMILIAR DE RISARALDA - COMFAMILIAR RISARALDA',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL SUR DEL TOLIMA CAFASUR',
	'Caja de compensacion familiar del norte del tolima comfaminorte',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL TOLIMA COMFATOLIMA',
	'CAJA DE COMPENSACIÓN FAMILIAR DE FENALCO DEL TOLIMA - COMFENALCO',
	'CAJA DE COMPENSACIÓN FAMILIAR COMFENALCO DEL VALLE DEL CAUCA - COMFENALCO VALLE',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL VALLE DEL CAUCA COMFAMILIAR ANDI - COMFANDI',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL PUTUMAYO - COMFAMILIAR PUTUMAYO',
	'CAJA DE COMPENSACIÓN FAMILIAR DE SAN ANDRES Y PROVIDENCIA, ISLAS CAJASAI',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL AMAZONAS CAFAMAZ',
	'CAJA DE COMPENSACIÓN FAMILIAR DE ARAUCA COMFIAR',
	'CAJA DE COMPENSACIÓN FAMILIAR CAMPESINA COMCAJA',
	'CAJA DE COMPENSACIÓN FAMILIAR DEL CASANARE - COMFACASANARE',
];
export const compensationFunds = compensations.map(compensation => ({
	value: compensation,
	label: compensation,
}));

const eps = [
	'COOSALUD ESS EPS-S',
	'NUEVA EPS S.A - NUEVA EMPRESA PROMOTORA DE SALUD NUEVA EPS S.A',
	'EPS-S MUTUAL SER',
	'COLMÉDICA EPS - ALIANSALUD DESDE EL 01/01/2011',
	'SALUD TOTAL S.A. ENTIDAD PROMOTORA DE SALUD',
	'ENTIDAD PROMOTORA DE SALUD SANITAS S.A.',
	'EPS-SURA',
	'ENTIDAD PROMOTORA DE SALUD FAMISANAR LIMITADA CAFAM-COLSUBSIDIO',
	'ENTIDAD PROMOTORA DE SALUD SERVICIO OCCIDENTAL DE SALUD S.A. S.O.S.',
	'SALUD MIA EPS',
	'COMFENALCO VALLE E.P.S.',
	'COMPENSAR ENTIDAD PROMOTORA DE SALUD',
	'EPM - Empresas publicas de medellin',
	'Fondo de pasivo social de ferrocarriles nacionales de colombia',
	'EPS-S CAJACOPI',
	'CAPRESOCA EPS',
	'Comfachoco',
	'EPS-CCFC COM GUAJIRA',
	'EPS-S COMFAORIENTE',
	'EPS Familiar de colombia (Antes ComfaSucre)',
	'ASMET SALUD EPS SAS',
	"ENTIDAD COOPERATIVA SOLIDARIA 'ECOOPSOS'",
	'CMRC RECAUDO FOSYGA-EMSSANAR E.S.S',
	'RECAUDO FOSYGA CAPITAL SALUD',
	'ALIANZA MEDELLIN ANTIOQUIA EPS SAS (SAVIA SALUD)',
	'DUSAKAWI EPS',
	"ASOCIACION INDIGENA DEL CAUDA 'A.I.C'",
	'ANAS WAYUU E P S I FOSYGA',
	'ENTIDAD PROMOTORA DE SALUD MALLAMAS',
	'ENTIDAD PROMOTORA DE SALUD PIJAOSALUD E',
	'EMP MUTUAL PARA EL DESAR ENDISALUD ESS',
	'COOSALUD EPS S.A.',
	'NUEVA EPS S.A.',
	'FUERZAS MILITARES',
	'POLICIA NACIONAL',
	'ECOPETROL',
	'MAGISTERIO',
	'UNIVERSIDAD DEL ATLANTICO',
	'UNIVERSIDAD INDUSTRIAL DE SANTANDER',
	'UNIVERSIDAD DEL VALLE',
	'UNIVERSIDAD NACIONAL DE COLOMBIA',
	'UNIVERSIDAD DEL CAUCA',
	'UNIVERSIDAD DE CARTAGENA',
	'UNIVERSIDAD DE ANTIOQUIA',
	'UNIVERSIDAD DE CORDOBA',
	'UNIVERSIDAD DE NARIÑO',
	'UNIVERSIDAD PEDAGOGICA Y TECNOLOGICA DE COLOMBIA - UPT',
];
export const epsList = eps.map(eps => ({ value: eps, label: eps }));

const pensions = [
	'Protección',
	'Porvenir',
	'Colpensiones',
	'Colfondos',
	'Old Mutual',
];
export const pensionFunds = pensions.map(pension => ({
	value: pension,
	label: pension,
}));

const redundancies = [
	'Protección',
	'Porvenir',
	'Colfondos',
	'Old Mutual',
	'Fondo Nacional del Ahorro',
	'Fondo de prestaciones sociales del magisterio',
];
export const redundancyFunds = redundancies.map(redundancy => ({
	value: redundancy,
	label: redundancy,
}));

const financialInstitutions = [
	'Bancamía',
	'Bancolombia',
	'Bancoomeva',
	'Banco agrario',
	'Banco av villas',
	'Banco caja social',
	'Banco credifinanciera',
	'Banco de bogotá',
	'Banco de occidente',
	'Banco falabella',
	'Banco finandina',
	'Banco GNB Sudameris',
	'Banco J.P. MORGAN',
	'Banco mundo mujer',
	'Banco pichincha',
	'Banco popular',
	'Banco santander',
	'Banco serfinanza',
	'Banco W',
	'BBVA',
	'Citibank',
	'Coopcentral',
	'Cooperativa confiar',
	'Cooperativa cootramed',
	'Cooperativa cotrafa',
	'Cooperativa de ahorro y crédito nacional',
	'Cooperativa financiera de antioquia',
	'Cooperativa utrahuilca',
	'Cooprofesores',
	'Davivienda',
	'Daviplata',
	'Mibanco',
	'Nequi',
	'Itaú',
	'Scotibank colpatria',
	'Juriscoop',
	'DALE',
	'Crediflores',
	'Lulo Bank',
	'Global66',
];
export const banks = financialInstitutions.map(bank => ({
	value: bank,
	label: bank,
}));

export const departmentsValues = [
	'Amazonas',
	'Antioquia',
	'Arauca',
	'Atlántico',
	'Bolívar',
	'Boyacá',
	'Caldas',
	'Caquetá',
	'Casanare',
	'Cauca',
	'Cesar',
	'Chocó',
	'Córdoba',
	'Cundinamarca',
	'Guainía',
	'Guaviare',
	'Huila',
	'La Guajira',
	'Magdalena',
	'Meta',
	'Nariño',
	'Norte de Santander',
	'Putumayo',
	'Quindío',
	'Risaralda',
	'San Andrés y Providencia',
	'Santander',
	'Sucre',
	'Tolima',
	'Valle del Cauca',
	'Vaupés',
	'Vichada',
	'Bogotá D.C.',
];
export const departments = departmentsValues.map(department => ({
	value: department,
	label: department,
}));

export function mapIdType(idType: string) {
	return soenacIdentificationsMapper[
		idType as keyof typeof soenacIdentificationsMapper
	];
}

const periods = [
	'Semanal',
	'Decenal',
	'Catorcenal',
	'Quincenal',
	'Mensual',
	'Otro',
];

export const periodsValues = payments.map(payment => ({
	value: payment,
	label: payment,
}));

export const periodsMapper = getMapper(periods);

export const posCreditNoteCorrections = [
	{
		label:
			'Devolución parcial de los bienes y/o no aceptación parcial del servicio',
		value: 'refund',
	},
	{ label: 'Anulación del documento equivalente electrónico', value: 'cancel' },
	{ label: 'Rebaja o descuento parcial o total', value: 'discount' },
	{ label: 'Otros', value: 'price_adjustment' },
	{ label: 'Ajuste de precio', value: 'others' },
];
export function getPosCreditNoteCorrectionSoenacId(
	concept: PosCreditNoteCorrectionType,
) {
	switch (concept) {
		case 'refund':
			return 16;
		case 'cancel':
			return 17;
		case 'discount':
			return 18;
		case 'price_adjustment':
			return 19;
		case 'others':
			return 20;
		default:
			throw new Error('Invalid concept');
	}
}
