-- AlterTable
ALTER TABLE "Cashier" ADD COLUMN     "totalByUserCard" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalByUserCash" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalByUserTransfer" DOUBLE PRECISION NOT NULL DEFAULT 0;
